openapi: 3.0.0
info:
  title: "Store"
  description: "API store"
  version: "1.0.0"
servers:
  - url: http://localhost:3000
    description: Local server
tags:
  - name: "Auth"
    description: "router auth"
  - name: "User"
    description: "router user"

paths:
  /auth/login:
    $ref: 'src/auth/auth.yaml#/components/Login'
  /auth/update_password:
    $ref: 'src/auth/auth.yaml#/components/UpdatePassword'
  /auth/check_token:
    $ref: 'src/auth/auth.yaml#/components/CheckToken'
  /auth/refresh_token:
    $ref: 'src/auth/auth.yaml#/components/RefreshToken'

  /user/:
    $ref: 'src/user/user.yaml#/components/User'
  /user/{id}:
    $ref: 'src/user/user.yaml#/components/UserId'
  
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Header authorization accessToken"
    bearerRefreshAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Header authorization refreshToken"
  schemas:
    Exceptions:
      type: object
      properties:
        error:
          type: string